[build]
builder = "nixpacks"
buildCommand = "javac -d out -sourcepath src $(find src -name '*.java')"

[build.nixpacks]
providers = ["java"]

[deploy]
startCommand = "java -cp out com.hotel.oop.HotelServerApp"
